_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.9.13
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.9.13
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
hidden_dim:
    value: 32
input_dim:
    value: 10
learning_rate:
    value: 0.01
np_seed:
    value: 12138
output_dim:
    value: 16
record_steps:
    value:
        - 5
        - 10
        - 15
        - 50
        - 100
        - 150
        - 200
        - 350
        - 500
steps:
    value: 500
top_k_pca_number:
    value: 5
torch_seed:
    value: 12138
wandb_project_name:
    value: Baseline
wandb_run_name:
    value: Baseline
