_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.9.13
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
                - 61
            "4": 3.9.13
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
hidden dim:
    value: 16
input dim:
    value: 16
learning rate:
    value: 0.01
output dim:
    value: 16
record steps:
    value:
        - 5
        - 10
        - 15
        - 50
        - 100
        - 150
        - 200
        - 350
        - 500
steps:
    value: 500
top k PCA number:
    value: 5
